### ISSUE TITLE
Setting sigma for adjacency matrix

### ISSUE THREAD

**Issue by yjhong89** [Kaimaoge/IGNNK#1]
Hello. I am YJ Hong.

In appendix material in IGNNK paper, there are different sigma settings for different datasets respectively when constructing corresponding adjacency matrix.

Can you let me know how you set sigma ? 

For example of NREL dataset, sigma for adjacency matrix is set to 7.5km and I cannot figure out why this value came out.

Thanks in advance.

Regards, YJ Hong.

**Comment by Kaimaoge** [comment]
Hi, sigma is set according to the variance of the distances between each node. So sigmas for different datasets are different.

**Comment by yjhong89** [comment]
@Kaimaoge 
Thanks for your answer.
BTW, there are thresholds for adjacency matrix for each dataset, how you set them ? (maybe measure degree fore each node...?)

Thanks.

Regards, YJ Hong

**Comment by Kaimaoge** [comment]
> @Kaimaoge 
> 
> Thanks for your answer.
> 
> BTW, there are thresholds for adjacency matrix for each dataset, how you set them ? (maybe measure degree fore each node...?)
> 
> 
> 
> Thanks.
> 
> 
> 
> Regards, YJ Hong

For METR-LA and PEMS-Bay, thresholds are 0.1. We set it according to the original paper using those two. We didn't use thresholds for other datasets.

**Comment by yjhong89** [comment]
@Kaimaoge 
Thanks!
